// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAOk1c2gE0DMMdM1ptCOrZugJhmYayeFY',
    appId: '1:803294236782:web:976981c83cee103976967f',
    messagingSenderId: '803294236782',
    projectId: 'rentalinid-f4c71',
    authDomain: 'rentalinid-f4c71.firebaseapp.com',
    storageBucket: 'rentalinid-f4c71.appspot.com',
    measurementId: 'G-1CKTPY9VP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZfRE8Y2XUOuv8TLHYq3iM_aKAbvxinns',
    appId: '1:803294236782:android:80c2fd750af72de376967f',
    messagingSenderId: '803294236782',
    projectId: 'rentalinid-f4c71',
    storageBucket: 'rentalinid-f4c71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5u8YWG0qrV0UbsKrrxN1gkZRRONMa8yg',
    appId: '1:803294236782:ios:9760779ef2e1971176967f',
    messagingSenderId: '803294236782',
    projectId: 'rentalinid-f4c71',
    storageBucket: 'rentalinid-f4c71.appspot.com',
    iosBundleId: 'com.example.rentalinId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5u8YWG0qrV0UbsKrrxN1gkZRRONMa8yg',
    appId: '1:803294236782:ios:9760779ef2e1971176967f',
    messagingSenderId: '803294236782',
    projectId: 'rentalinid-f4c71',
    storageBucket: 'rentalinid-f4c71.appspot.com',
    iosBundleId: 'com.example.rentalinId',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAOk1c2gE0DMMdM1ptCOrZugJhmYayeFY',
    appId: '1:803294236782:web:3eafc933853463ea76967f',
    messagingSenderId: '803294236782',
    projectId: 'rentalinid-f4c71',
    authDomain: 'rentalinid-f4c71.firebaseapp.com',
    storageBucket: 'rentalinid-f4c71.appspot.com',
    measurementId: 'G-VVBWH6NYN1',
  );

}